package servlets;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.http.*;

import bean.LibrarianBean;
import dao.LibrarianDao;

public class EditLibrarianForm extends HttpServlet {
	
	protected void doGet(HttpServletRequest req, HttpServletResponse res) throws IOException
	{
		int id = Integer.parseInt(req.getParameter("id"));
		LibrarianBean bean = LibrarianDao.viewById(id);
		
		PrintWriter pw = res.getWriter();
		pw.println("<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "<meta charset=\"ISO-8859-1\">\r\n"
				+ "<title>Edit Librarian Form</title>\r\n"
				+ "<style>\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "	background-color:#fbf3e4;\r\n"
				+ "}\r\n"
				+ "ul{\r\n"
				+ "	list-style-type:none;\r\n"
				+ "	margin:0;\r\n"
				+ "	padding:0;\r\n"
				+ "	overflow:hidden;\r\n"
				+ "	background-color: #333;\r\n"
				+ "}\r\n"
				+ "li{\r\n"
				+ "	float:left;\r\n"
				+ "}\r\n"
				+ "li a{\r\n"
				+ "	display:block;\r\n"
				+ "	color:white;\r\n"
				+ "	text-align:center;\r\n"
				+ "	padding:14px 16px;\r\n"
				+ "	text-decoration:none;\r\n"
				+ "	font-size:17px;\r\n"
				+ "}\r\n"
				+ "li a:not(.logo){\r\n"
				+ "	margin-top:2px;\r\n"
				+ "}\r\n"
				+ "li a:hover:not(.logo){\r\n"
				+ "	background-color:#111;\r\n"
				+ "}\r\n"
				+ ".logo{\r\n"
				+ "	margin:0px 20px;\r\n"
				+ "	color:#ffff66;\r\n"
				+ "	font-size:19px;\r\n"
				+ "}\r\n"
				+ ".main{\r\n"
				+ "	width:100%;\r\n"
				+ "	height:auto;\r\n"
				+ "	background:url(\"images/lib2.jpg\");\r\n"
				+ "	background-repeat:no-repeat;\r\n"
				+ "	background-size:cover;\r\n"
				+ "	background-color:#3e3e41;\r\n"
				+ "  	background-blend-mode: screen;\r\n"
				+ "  	margin-top:-15px;\r\n"
				+ "  	padding-bottom:15vh;\r\n"
				+ "}\r\n"
				+ ".section-heading{\r\n"
				+ "	font-size:34px;\r\n"
				+ "	color:white;\r\n"
				+ "	padding:50px 20px 10px 70px;\r\n"
				+ "}\r\n"
				+ "form{\r\n"
				+ "	background-color:rgba(255, 255, 255, 0.7);\r\n"
				+ "	padding:20px;\r\n"
				+ "	margin-left:90px;\r\n"
				+ "	width:30%;\r\n"
				+ "}\r\n"
				+ "input{\r\n"
				+ "	width:95%;\r\n"
				+ "	height:25px;\r\n"
				+ "	border:1px solid gray;\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	padding:2px 10px;\r\n"
				+ "	margin-top:3px;\r\n"
				+ "}\r\n"
				+ "label{\r\n"
				+ "	font-size:19px;\r\n"
				+ "}\r\n"
				+ "input[type=submit]{\r\n"
				+ "	background-color:#0077b3;\r\n"
				+ "	color:white;\r\n"
				+ "	font-weight:400;\r\n"
				+ "	font-size:17px;\r\n"
				+ "	width:80px;\r\n"
				+ "	padding:5px;\r\n"
				+ "	height:auto;\r\n"
				+ "	margin-top:10px;\r\n"
				+ "}\r\n"
				+ "</style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "\r\n"
				+ "<ul>\r\n"
				+ "	<li><a href=\"#\" class=\"logo\"><b>e-Library</b></a></li>\r\n"
				+ "	<li><a href=\"admin.html\">Home</a></li>\r\n"
				+ "	<li><a href=\"addLibrarian.html\">Add Librarian</a></li>\r\n"
				+ "	<li><a href=\"viewLibrarian.jsp\">View Librarian</a></li>\r\n"
				+ "	<li><a href=\"index.html\">Logout</a></li>\r\n"
				+ "</ul>\r\n"
				+ "\r\n"
				+ "<div class=\"main\">\r\n"
				+ "	<h1 class=\"section-heading\">Edit Librarian</h1>\r\n"
				+ "	<form action=\"editlibrarian\" method=\"post\">\r\n"
				+ "		<input type=\"hidden\" name=\"id\" value="+ bean.getId() +"><br><br>\r\n"
				+ "		<label>Name</label><br>\r\n"
				+ "		<input type=\"text\" name=\"name\" value="+ bean.getName() +"><br><br>\r\n"
				+ "		<label>Email address</label><br>\r\n"
				+ "		<input type=\"email\" name=\"email\" value="+ bean.getEmail() +"><br><br>\r\n"
				+ "		<label>Password</label><br>\r\n"
				+ "		<input type=\"password\" name=\"pwd\" value="+ bean.getPassword() +"><br><br>\r\n"
				+ "		<label>Mobile Number</label><br>\r\n"
				+ "		<input type=\"number\" name=\"mob\" value="+ bean.getMobile() +"><br><br>\r\n"
				+ "		<input type=\"submit\" value=\"Update\">\r\n"
				+ "	</form>\r\n"
				+ "</div>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</body>\r\n"
				+ "</html>");
	}

}
